// Enum para as ações (actions)
export enum UrlsEnum {
  BASE_PROD = "https://pet-system-backend-42e2abda25d2.herokuapp.com/api/v1/pet",
  AUTH = "/sys/auth/login",
  ME = "/users/me",
  COMPANIES = "/companies",
  PRODUCTS = "/products",
  FORGET = "/sys/auth/forget",
  USERS_PASSWORD = "/users/password",
  USERS_ME = "/users/me",
  USERS = "/users",
  USERS_CURRENT = "/users/current",
  CATEGORIES = "/categories",
  PROFILES = "/profiles",
  CUSTOMERS = "/customers",
  PETS = "/pets",
  DOGS = "/dogs",
  USER_PROFILE = "/users/profile",
  SCHEDULES = "/schedules",
  APPOINTMENT = "/appointments",
  APPOINTMENT_MONTH = `/appointments/month`,
  APPOINTMENT_DAY = "/appointments/day",
  APPOINTMENT_SCHEDULE = "/appointments/schedule",
  APPOINTMENT_STATUS = "/appointments/status",
}
